# Generated by Django 5.0.6 on 2024-06-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_employeeidsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empId',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
